- name: Create pods using deployment 
  hosts: kubernetes 
  # become: true
  # user: ubuntu
 
  tasks: 
  - name: delete the previous deployment
    command: /usr/local/bin/kubectl delete deployment.apps/cicd-deployment

  - name: create a deployment
    command: /usr/local/bin/kubectl apply -f /Users/freelife/dev_inflearn/jenkins_cicd_script/k8s_script/cicd-devops-deployment.yml